### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by micahchoo** [KnowledgeGarden/lite-net-3#27]
I am getting this error when i launch it

self is not defined
```
ReferenceError: self is not defined
    at isPrivate (E:\note-lite\lite-net-3\routes\helper.js:25:13)
    at Layer.handle [as handle_request] (E:\note-lite\lite-net-3\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\note-lite\lite-net-3\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\note-lite\lite-net-3\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\note-lite\lite-net-3\node_modules\express\lib\router\layer.js:95:5)
    at E:\note-lite\lite-net-3\node_modules\express\lib\router\index.js:281:22
    at param (E:\note-lite\lite-net-3\node_modules\express\lib\router\index.js:354:14)
    at param (E:\note-lite\lite-net-3\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (E:\note-lite\lite-net-3\node_modules\express\lib\router\index.js:410:3)
    at next (E:\note-lite\lite-net-3\node_modules\express\lib\router\index.js:275:10)
```

**Comment by KnowledgeGarden** [comment]
Interesting.
What are the conditions for the error? Since it's been running fine for a long time, need to understand what's different.

**Comment by aadityabhatia** [comment]
I did a fresh checkout and ran the project. Unable to reproduce the error with NodeJS v19.3.0. Additional information will help troubleshoot.
- What version of NodeJS are you using?
- Did you run using either `npm start` or `node bin/www`?
- Did the error message appear on the command line right away or after you navigated to the webpage? did it involve any additional steps?
- Does the error persist on a fresh checkout? Does clearing the database files under `./data` help?

**Comment by micahchoo** [comment]
Fixed it, i had to delete the .keep file remaining in the data folder. Thanks!

**Comment by KnowledgeGarden** [comment]
@micahchoo please feel free to use this thread to keep us posted on what you learn.
It's been my opinion that this project is ripe for an upgrade to something like Postgres, and a few improvements to the UX. Your thoughts will be appreciated. Thanks - Jack

**Comment by micahchoo** [comment]
I came in cold from a link about other open source PKMs. So i'm still trying to figure out how to contextualise it
